---
title: "Agriculture, fisheries and rural statistics"
author: "`r as.character(Sys.info()[7])`"
date: "`r Sys.Date()`"
sgtemplates:
  footer:
    link:
      - href: "privacy.html"
        text: "Privacy"
      - href: "cookies.html"
        text: "Cookies"
      - href: "accessibility.html"
        text: "Accessibility"
      - href: "contact.html"
        text: "Contact"
  header:
    phase_banner:
      tag: "WIP"
      text: "This is a work in progress."
    site_branding: "Scottish Government"
  metadata:
    label: "Collection"
  navigation:
    breadcrumb_trail:
      - text: "Home"
    toc:
      sticky: false
  seo:
    description: "SEO (search engine optimisation) description"
    keywords: "SEO, keywords, comma, separated"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

We provides statistical reports and economic information on agriculture and fisheries, including results from the main agricultural census and surveys, information on farming incomes and the annual report of sea fisheries statistics.

## Overview of Scottish agriculture

-   [Economic Report on Scottish Agriculture](https://www.gov.scot/collections/economic-report-on-scottish-agriculture/)

An annual publication providing statistics and commentary on all parts of the Scottish Agricultural Economy.

-   [Agriculture Facts and Figures](https://www.gov.scot/collections/agricultural-facts-and-figures/)

A quick reference leaflet of agricultural statistics.

## Agricultural census results

-   [Results of the June Agricultural Census](https://www.gov.scot/collections/june-scottish-agricultural-census/)

Including results of the latest June Agricultural Census, with comparative annual data back as far as 2006.

-   [Abstract of Scottish Agricultural Statistics](https://www.gov.scot/publications/abstract-of-scottish-agricultural-statistics-1982-2017/)

A time series of June agricultural census results providing Scottish agricultural land use, livestock and labour statistics from 1982.

-   [Results from December Agricultural Surveys](https://www.gov.scot/publications/results-2019-december-agricultural-survey/)

Provides Scotland totals for the annual December survey, based on data from larger agricultural holdings together with estimates for smaller farms

## Farm incomes, subsidies and borrowing statistics

-   [Farm Business Income](https://www.gov.scot/collections/scottish-farm-business-income-fbi-annual-estimates/)

Annual Estimates of farm business level income. Prior to 2014 these were included in the Farm Income Estimates (below).

-   [Farm Income Estimates](https://www.gov.scot/collections/scottish-farm-business-income-fbi-annual-estimates/)

Estimates of Total Income From Farming (TIFF) for 2016, an initial estimate of 2017 TIFF.

<!-- [Records going back to 1999 may be accessed at our online archive.](https://webarchive.nrscotland.gov.uk/20200114064159/https://www2.gov.scot/Topics/Statistics/Browse/Agriculture-Fisheries/PubFinalResultsJuneCensus) -->
